### ISSUE TITLE
Solr startup error 

### ISSUE THREAD

**Issue by jpbuttet** [keensoft/alfresco-docker-template#5]
Hello,

I've been running Alfresco for about 5 years but the cool Docker technology is quite new for me.
Your Docker template looks like a very interesting solution that enables quick and easy Alfresco deployment along with https frontend.

Thank you very much for your work.

I'm trying /templates/201806-GA/.
- I set permission for UID 1001 for the solr-data folder in the host
- I could make a docker-compose up -d then checked with dicker ps command.
- Alfresco share is accessible via the web interface but something looks like wrong with solr.

The solr log shows:

org.apache.solr.common.SolrException: Error CREATEing SolrCore 'alfresco': Unable to create core [alfresco] Caused by: /opt/alfresco-search-services/data/alfresco

org.apache.solr.common.SolrException: java.nio.file.AccessDeniedException: /opt/alfresco-search-services/data/alfresco
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:903)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:776)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:842)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:779)
	at org.alfresco.solr.AlfrescoCoreAdminHandler.createAndRegisterNewCore(AlfrescoCoreAdminHandler.java:552)
	at org.alfresco.solr.AlfrescoCoreAdminHandler.newCore(AlfrescoCoreAdminHandler.java:458)
	at org.alfresco.solr.AlfrescoCoreAdminHandler.newDefaultCore(AlfrescoCoreAdminHandler.java:385)
	at org.alfresco.solr.AlfrescoCoreAdminHandler.setupNewDefaultCores(AlfrescoCoreAdminHandler.java:141)
	at org.alfresco.solr.AlfrescoCoreAdminHandler.lambda$startup$0(AlfrescoCoreAdminHandler.java:111)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: java.nio.file.AccessDeniedException: /opt/alfresco-search-services/data/alfresco
	at org.apache.solr.core.SolrCore.initSnapshotMetaDataManager(SolrCore.java:439)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:844)

Could you please help to to solve this issue ?

Thanks in advance.

Jean-Pierre

**Comment by angelborroy-ks** [comment]
Probably is a better choice to use this project as base:

https://github.com/keensoft/docker-alfresco 

@ainsofs provided a permissions set up at https://github.com/keensoft/docker-alfresco/issues/1

**Comment by jpbuttet** [comment]
Hi angelborroy-ks

I've been struggling quite a bit to find a dockerized alfresco that works fine.
I've test many recent versions that suffer from a well know bug:
https://hub.alfresco.com/t5/alfresco-content-services-forum/resize-the-thumbnails-on-gallery-view/m-p/28036

I can not live with this bug.

I run now a customized version of your 201702-GA  template. I like this template very much, it's quite flexible and useful. Thank you for your very interesting work.

Everything is okay with the exception of following:
Are you aware of this issue that I raised fee weeks ago ?

https://hub.alfresco.com/t5/alfresco-content-services-forum/sending-pdf-to-alfresco-via-cifs-doesn-t-fire-metadata-extracter/m-p/293588#M16467

Any idea that would help me to solve this issue ?

Best regards.

Jean-Pierre Buttet
